import type { Player, Team } from "./types";

export const PLAYERS: Player[] = [
  {
    id: "p1",
    slug: "minh-le",
    name: "Lê Hoàng Minh",
    username: "minhle10",
    avatar: "https://i.pravatar.cc/300?img=12",
    cover:
      "https://images.unsplash.com/photo-1577471488278-16eec37ffcc2?auto=format&fit=crop&w=1600&q=80",
    city: "Hanoi",
    country: "Vietnam",
    position: "ST",
    altPositions: ["LW", "CAM"],
    foot: "Right",
    height: 178,
    weight: 72,
    age: 24,
    yearsPlaying: 12,
    rating: 86,
    stats: {
      pace: 88,
      shooting: 87,
      passing: 79,
      dribbling: 85,
      defending: 42,
      physical: 75,
      stamina: 84,
    },
    bio: "Clinical finisher with a thirst for late winners. Plays Saturday 7-a-side and Sunday 11-a-side.",
    bioVi:
      "Tiền đạo dứt điểm sắc bén, chuyên ghi bàn phút cuối. Đá 7-a-side thứ Bảy và 11-a-side Chủ nhật.",
    teamId: "t1",
    availability: ["Tue", "Thu", "Sat", "Sun"],
    achievements: [
      { year: 2024, title: "Vua phá lưới Hanoi Sunday League" },
      { year: 2023, title: "Cầu thủ xuất sắc nhất giải sân 7 Friday" },
    ],
    matchHistory: [
      { date: "2026-05-04", opponent: "Saigon Strikers", result: "W", score: "3-1", goals: 2, assists: 1 },
      { date: "2026-04-27", opponent: "Da Nang FC", result: "D", score: "2-2", goals: 1 },
      { date: "2026-04-20", opponent: "Hai Phong United", result: "W", score: "4-0", goals: 1, assists: 2 },
      { date: "2026-04-13", opponent: "Hue Dragons", result: "L", score: "1-2", goals: 1 },
    ],
  },
  {
    id: "p2",
    slug: "ngoc-pham",
    name: "Phạm Thị Ngọc",
    username: "ngoc.cb",
    avatar: "https://i.pravatar.cc/300?img=47",
    cover:
      "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1600&q=80",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    position: "CB",
    altPositions: ["CDM"],
    foot: "Left",
    height: 168,
    weight: 60,
    age: 27,
    yearsPlaying: 9,
    rating: 82,
    stats: {
      pace: 70,
      shooting: 55,
      passing: 78,
      dribbling: 68,
      defending: 88,
      physical: 80,
      stamina: 82,
    },
    bio: "Composed centre back, reads the game and starts attacks with crisp passing.",
    bioVi:
      "Trung vệ điềm đạm, đọc trận đấu tốt và mở bóng bằng những đường chuyền sắc nét.",
    teamId: "t2",
    availability: ["Mon", "Wed", "Fri", "Sat"],
    achievements: [
      { year: 2025, title: "Vô địch Cúp bóng đá nữ Sài Gòn" },
    ],
    matchHistory: [
      { date: "2026-05-03", opponent: "Mekong Warriors", result: "W", score: "2-0", assists: 1 },
      { date: "2026-04-26", opponent: "Bien Hoa FC", result: "W", score: "1-0" },
      { date: "2026-04-19", opponent: "Vung Tau Sharks", result: "D", score: "1-1" },
    ],
  },
  {
    id: "p3",
    slug: "kien-tran",
    name: "Trần Anh Kiên",
    username: "kien.gk",
    avatar: "https://i.pravatar.cc/300?img=8",
    cover:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1600&q=80",
    city: "Da Nang",
    country: "Vietnam",
    position: "GK",
    altPositions: [],
    foot: "Right",
    height: 188,
    weight: 80,
    age: 29,
    yearsPlaying: 15,
    rating: 84,
    stats: {
      pace: 60,
      shooting: 30,
      passing: 70,
      dribbling: 50,
      defending: 85,
      physical: 88,
      stamina: 78,
      goalkeeping: 88,
    },
    bio: "Shot-stopper with a long, accurate distribution. Available for weekend pickups along the central coast.",
    bioVi:
      "Thủ môn phản xạ tốt và phát bóng chính xác. Sẵn sàng cho các trận pickup cuối tuần ở miền Trung.",
    availability: ["Sat", "Sun"],
    achievements: [
      { year: 2024, title: "Găng tay vàng giải sân 7 miền Trung" },
    ],
    matchHistory: [
      { date: "2026-05-02", opponent: "Hue Dragons", result: "W", score: "3-0" },
      { date: "2026-04-25", opponent: "Quang Nam FC", result: "L", score: "1-2" },
    ],
  },
  {
    id: "p4",
    slug: "linh-vu",
    name: "Vũ Mai Linh",
    username: "linh.cam",
    avatar: "https://i.pravatar.cc/300?img=32",
    cover:
      "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=1600&q=80",
    city: "Hanoi",
    country: "Vietnam",
    position: "CAM",
    altPositions: ["CM", "RW"],
    foot: "Both",
    height: 165,
    weight: 56,
    age: 22,
    yearsPlaying: 10,
    rating: 80,
    stats: {
      pace: 80,
      shooting: 75,
      passing: 84,
      dribbling: 88,
      defending: 50,
      physical: 65,
      stamina: 86,
    },
    bio: "Creative number 10 — through balls, set pieces, and a wicked left foot.",
    bioVi:
      "Số 10 sáng tạo — chuyên đường chuyền vượt tuyến, đá phạt, và một cú trái chân hiểm.",
    teamId: "t1",
    availability: ["Wed", "Fri", "Sun"],
    achievements: [{ year: 2025, title: "Tuyển chọn U23 thành phố" }],
    matchHistory: [
      { date: "2026-05-04", opponent: "Saigon Strikers", result: "W", score: "3-1", assists: 2 },
    ],
  },
  {
    id: "p5",
    slug: "tuan-do",
    name: "Đỗ Quốc Tuấn",
    username: "tuan.lw",
    avatar: "https://i.pravatar.cc/300?img=14",
    cover:
      "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1600&q=80",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    position: "LW",
    altPositions: ["ST"],
    foot: "Right",
    height: 173,
    weight: 68,
    age: 20,
    yearsPlaying: 8,
    rating: 78,
    stats: {
      pace: 92,
      shooting: 74,
      passing: 70,
      dribbling: 84,
      defending: 38,
      physical: 60,
      stamina: 88,
    },
    bio: "Pacey winger who loves cutting in on his right.",
    bioVi: "Tiền vệ cánh tốc độ, sở trường cắt vào trong sút chân thuận phải.",
    teamId: "t2",
    availability: ["Mon", "Wed", "Sat"],
    achievements: [],
    matchHistory: [
      { date: "2026-05-03", opponent: "Mekong Warriors", result: "W", score: "2-0", goals: 1 },
    ],
  },
  {
    id: "p6",
    slug: "huy-nguyen",
    name: "Nguyễn Quang Huy",
    username: "huy.cdm",
    avatar: "https://i.pravatar.cc/300?img=51",
    cover:
      "https://images.unsplash.com/photo-1542144582-1ba00456b5e3?auto=format&fit=crop&w=1600&q=80",
    city: "Hanoi",
    country: "Vietnam",
    position: "CDM",
    altPositions: ["CB"],
    foot: "Right",
    height: 180,
    weight: 75,
    age: 31,
    yearsPlaying: 18,
    rating: 81,
    stats: {
      pace: 65,
      shooting: 60,
      passing: 82,
      dribbling: 70,
      defending: 84,
      physical: 82,
      stamina: 80,
    },
    bio: "Defensive midfielder who breaks up play and recycles possession.",
    bioVi: "Tiền vệ phòng ngự — cắt bóng và luân chuyển bóng nhịp nhàng.",
    availability: ["Sat", "Sun"],
    achievements: [{ year: 2022, title: "Vô địch Hanoi League" }],
    matchHistory: [],
  },
  {
    id: "p7",
    slug: "anh-tran",
    name: "Trần Hoài Anh",
    username: "anh.rb",
    avatar: "https://i.pravatar.cc/300?img=65",
    cover:
      "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1600&q=80",
    city: "Hai Phong",
    country: "Vietnam",
    position: "RB",
    altPositions: ["RW", "CB"],
    foot: "Right",
    height: 175,
    weight: 70,
    age: 26,
    yearsPlaying: 11,
    rating: 76,
    stats: {
      pace: 84,
      shooting: 60,
      passing: 74,
      dribbling: 72,
      defending: 78,
      physical: 72,
      stamina: 87,
    },
    bio: "Attacking right back, never stops running.",
    bioVi: "Hậu vệ cánh phải tấn công, không biết mệt.",
    availability: ["Tue", "Thu", "Sun"],
    achievements: [],
    matchHistory: [],
  },
  {
    id: "p8",
    slug: "hoa-pham",
    name: "Phạm Bích Hoa",
    username: "hoa.ws",
    avatar: "https://i.pravatar.cc/300?img=23",
    cover:
      "https://images.unsplash.com/photo-1552072804-dc1cde9015a8?auto=format&fit=crop&w=1600&q=80",
    city: "Da Nang",
    country: "Vietnam",
    position: "RW",
    altPositions: ["LW", "ST"],
    foot: "Left",
    height: 162,
    weight: 54,
    age: 19,
    yearsPlaying: 7,
    rating: 75,
    stats: {
      pace: 90,
      shooting: 70,
      passing: 68,
      dribbling: 82,
      defending: 35,
      physical: 58,
      stamina: 86,
    },
    bio: "Rising winger with U19 squad experience.",
    bioVi: "Tiền vệ cánh trẻ, có kinh nghiệm khoác áo U19.",
    availability: ["Sat"],
    achievements: [{ year: 2024, title: "Đội U19 Đà Nẵng" }],
    matchHistory: [],
  },
];

export const TEAMS: Team[] = [
  {
    id: "t1",
    slug: "hanoi-rovers",
    name: "Hanoi Rovers",
    vnName: "Hanoi Rovers",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=hanoirovers&backgroundColor=059669",
    cover:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1600&q=80",
    city: "Hanoi",
    country: "Vietnam",
    format: "11-a-side",
    level: "Semi-pro",
    founded: 2017,
    rating: 88,
    members: 22,
    capacity: 26,
    openSlots: 4,
    bio: "A semi-pro Sunday league side from West Lake. Looking for a left back and a backup goalkeeper.",
    bioVi:
      "Đội bán chuyên giải Chủ nhật ở khu Tây Hồ. Đang cần 1 hậu vệ trái và 1 thủ môn dự bị.",
    schedule: "Chủ nhật · 09:00 · Sân Tây Hồ",
    achievements: [
      { year: 2024, title: "Vô địch Hanoi Sunday League" },
      { year: 2023, title: "Á quân Sunday League" },
    ],
    recentForm: ["W", "W", "D", "W", "L"],
    captainId: "p1",
    memberIds: ["p1", "p4", "p6"],
  },
  {
    id: "t2",
    slug: "saigon-strikers",
    name: "Saigon Strikers",
    vnName: "Saigon Strikers",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=saigonstrikers&backgroundColor=f97316",
    cover:
      "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1600&q=80",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    format: "7-a-side",
    level: "Competitive",
    founded: 2020,
    rating: 84,
    members: 14,
    capacity: 18,
    openSlots: 4,
    bio: "Competitive 7s side that plays the District 2 league every Wednesday and Saturday.",
    bioVi:
      "Đội thi đấu 7-a-side đỉnh cao ở giải Quận 2, sân chính thứ Tư & thứ Bảy hàng tuần.",
    schedule: "Thứ 4 & Thứ 7 · 19:30 · Trung tâm thể thao Quận 2",
    achievements: [{ year: 2025, title: "Hạng 3 giải Quận 2" }],
    recentForm: ["W", "L", "W", "W", "D"],
    captainId: "p2",
    memberIds: ["p2", "p5"],
  },
  {
    id: "t3",
    slug: "danang-coastal",
    name: "Da Nang Coastal",
    vnName: "Da Nang Coastal",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=danangcoastal&backgroundColor=06b6d4",
    cover:
      "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1600&q=80",
    city: "Da Nang",
    country: "Vietnam",
    format: "5-a-side",
    level: "Casual",
    founded: 2022,
    rating: 72,
    members: 8,
    capacity: 12,
    openSlots: 4,
    bio: "Friendly 5-a-side group on My Khe beach, all skill levels welcome.",
    bioVi:
      "Nhóm 5-a-side thân thiện ở bãi biển Mỹ Khê, chào đón mọi trình độ.",
    schedule: "Sáng thứ 7 · Sân Mỹ Khê",
    achievements: [],
    recentForm: ["D", "W", "L", "D", "W"],
    captainId: "p3",
    memberIds: ["p3"],
  },
  {
    id: "t4",
    slug: "haiphong-united",
    name: "Hai Phong United",
    vnName: "Hai Phong United",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=haiphong&backgroundColor=dc2626",
    cover:
      "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=1600&q=80",
    city: "Hai Phong",
    country: "Vietnam",
    format: "11-a-side",
    level: "Amateur",
    founded: 2015,
    rating: 78,
    members: 24,
    capacity: 26,
    openSlots: 2,
    bio: "Long-running amateur 11s team. Two-time city cup finalists.",
    bioVi:
      "Đội bóng 11 người lâu năm. Hai lần vào chung kết cúp thành phố.",
    schedule: "Chủ nhật · 16:00 · Sân Lạch Tray",
    achievements: [
      { year: 2023, title: "Á quân Cúp Hải Phòng" },
      { year: 2021, title: "Á quân Cúp Hải Phòng" },
    ],
    recentForm: ["W", "L", "D", "W", "W"],
    captainId: "p7",
    memberIds: ["p7"],
  },
  {
    id: "t5",
    slug: "hue-dragons",
    name: "Hue Dragons",
    vnName: "Hue Dragons",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=huedragons&backgroundColor=8b5cf6",
    cover:
      "https://images.unsplash.com/photo-1542144582-1ba00456b5e3?auto=format&fit=crop&w=1600&q=80",
    city: "Hue",
    country: "Vietnam",
    format: "7-a-side",
    level: "Amateur",
    founded: 2019,
    rating: 75,
    members: 12,
    capacity: 16,
    openSlots: 4,
    bio: "Mid-week 7s side. Looking for an attacking midfielder and a striker.",
    bioVi: "Đội 7s đá giữa tuần. Cần 1 tiền vệ tấn công và 1 tiền đạo.",
    schedule: "Thứ 3 · 18:00 · Sân TP Huế",
    achievements: [],
    recentForm: ["L", "D", "W", "L", "W"],
    captainId: "p4",
    memberIds: [],
  },
  {
    id: "t6",
    slug: "mekong-warriors",
    name: "Mekong Warriors",
    vnName: "Mekong Warriors",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=mekong&backgroundColor=eab308",
    cover:
      "https://images.unsplash.com/photo-1552072804-dc1cde9015a8?auto=format&fit=crop&w=1600&q=80",
    city: "Can Tho",
    country: "Vietnam",
    format: "11-a-side",
    level: "Amateur",
    founded: 2018,
    rating: 73,
    members: 19,
    capacity: 26,
    openSlots: 7,
    bio: "Mekong delta team rebuilding for the new season — open to half the squad.",
    bioVi: "Đội miền Tây đang tái thiết lực lượng — mở 7 suất cho mùa mới.",
    schedule: "Thứ 7 · 17:30 · Sân vận động Cần Thơ",
    achievements: [],
    recentForm: ["L", "D", "W", "L", "L"],
    captainId: "p8",
    memberIds: [],
  },
];

export function getPlayerById(id: string): Player | undefined {
  return PLAYERS.find((p) => p.id === id || p.slug === id);
}

export function getTeamById(id: string): Team | undefined {
  return TEAMS.find((t) => t.id === id || t.slug === id);
}

export function getTeamMembers(team: Team): Player[] {
  return PLAYERS.filter((p) => team.memberIds.includes(p.id));
}
